### ISSUE TITLE
Consolidate Pinned Tabs

### ISSUE THREAD

**Issue by ryanatsubskribe** [hacktoolkit/organize-tabs-chrome-extension#6]
### STEPS TO REPRODUCE

1. Have more than one window open with many tabs, some pinned tabs in at least one window
2. Select **Consolidate Tabs** 

### EXPECTED RESULTS

- Tabs are consolidated in one window

### ACTUAL RESULTS

- Pinned tabs are consolidated in one window, other tabs are consolidated in another window.

**Comment by jontsai** [comment]
This is resolved by #7 

Note however that there is a slight inconvenience that moved pinned tabs become unpinned, due to a bug in the underlying Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=876460&q=chrome.tabs.move&can=2)

Will be tracking it and trying to assist the Chromium team to resolve it.

Version 0.7.0 has been submitted for release to the Chrome Web Store, and will become available once it is approved by the Chrome Web Store reviewers: https://chrome.google.com/webstore/detail/organize-tabs/ebnlpacdgjnofakgfgbildmjdhbibnpa
